export const CATEGORIES_ACTION_TYPES = {
  // SET_CATEGORIES: 'SET_CATEGORIES',
  FETCH_CATEGORIES_START: 'categories/FETCH_CATEGORIES_START',
  FETCH_CATEGORIES_SUCCEEDED: 'categories/FETCH_CATEGORIES_SUCCEEDED',
  FETCH_CATEGORIES_FAILED: 'categories/FETCH_CATEGORIES_FAILED',
};
